version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=redway
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: